defaults: &defaults
  host: localhost
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: false

development:
  <<: *defaults
  database: my_dev

test:
  <<: *defaults
  database: my_test

